/**
 * QR codes generated by PremierPass encode the ticket code prefixed with
 * "PREMIERPASS-". Scanners must accept both the prefixed QR payload and the
 * raw ticket code typed manually.
 */
export const TICKET_QR_PREFIX = "PREMIERPASS-";

export const buildTicketQrValue = (ticketCode: string) =>
  `${TICKET_QR_PREFIX}${ticketCode.trim().toUpperCase()}`;

export const normalizeTicketCode = (raw: string) => {
  const value = (raw || "").trim().toUpperCase();
  return value.startsWith(TICKET_QR_PREFIX)
    ? value.slice(TICKET_QR_PREFIX.length)
    : value;
};