// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-events.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-events.ts
var list_events_default = defineTool({
  name: "list_events",
  title: "Listar eventos",
  description: "Lista eventos publicados da PremierPass, com busca opcional por t\xEDtulo, cidade ou categoria.",
  inputSchema: {
    search: z.string().trim().min(1).optional().describe("Texto para buscar no t\xEDtulo do evento."),
    city: z.string().trim().min(1).optional().describe("Filtrar por cidade."),
    category: z.string().trim().min(1).optional().describe("Filtrar por categoria."),
    limit: z.number().int().min(1).max(50).default(20).describe("N\xFAmero m\xE1ximo de eventos retornados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, city, category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("events").select("id, title, slug, status, start_date, end_date, city, state, category, is_online, venue_name, short_description").eq("status", "published").order("start_date", { ascending: true }).limit(limit ?? 20);
    if (search) query = query.ilike("title", `%${search}%`);
    if (city) query = query.ilike("city", `%${city}%`);
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-event.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_event_default = defineTool2({
  name: "get_event",
  title: "Detalhes do evento",
  description: "Retorna os detalhes de um evento e os seus tipos de ingresso ativos, por id ou slug.",
  inputSchema: {
    event_id: z2.string().uuid().optional().describe("ID (UUID) do evento."),
    slug: z2.string().trim().min(1).optional().describe("Slug do evento.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ event_id, slug }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    if (!event_id && !slug) return { content: [{ type: "text", text: "Informe event_id ou slug." }], isError: true };
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("events").select("*").limit(1);
    query = event_id ? query.eq("id", event_id) : query.eq("slug", slug);
    const { data: event, error } = await query.maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!event) return { content: [{ type: "text", text: "Evento n\xE3o encontrado." }], isError: true };
    const { data: ticketTypes, error: ttError } = await supabase.from("ticket_types").select("id, name, description, price, quantity_available, quantity_sold, max_per_order, is_active, sale_start, sale_end").eq("event_id", event.id).eq("is_active", true).order("position", { ascending: true });
    if (ttError) return { content: [{ type: "text", text: ttError.message }], isError: true };
    const payload = { event, ticket_types: ticketTypes ?? [] };
    return { content: [{ type: "text", text: JSON.stringify(payload) }], structuredContent: payload };
  }
});

// src/lib/mcp/tools/list-my-tickets.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_tickets_default = defineTool3({
  name: "list_my_tickets",
  title: "Meus ingressos",
  description: "Lista os ingressos do usu\xE1rio autenticado, com o evento correspondente.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).default(50).describe("N\xFAmero m\xE1ximo de ingressos retornados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("tickets").select("id, ticket_code, status, is_used, used_at, checked_in_at, is_complimentary, created_at, events(id, title, start_date, city, venue_name), ticket_types(id, name, price)").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data ?? []) }], structuredContent: { tickets: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-my-orders.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_my_orders_default = defineTool4({
  name: "list_my_orders",
  title: "Meus pedidos",
  description: "Lista os pedidos de compra do usu\xE1rio autenticado, com status de pagamento e valores.",
  inputSchema: {
    status: z4.string().trim().min(1).optional().describe("Filtrar por status do pedido (ex.: pending, paid)."),
    limit: z4.number().int().min(1).max(100).default(20).describe("N\xFAmero m\xE1ximo de pedidos retornados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("orders").select("id, status, total_amount, service_fee, payment_method, paid_at, created_at, events(id, title, start_date)").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data ?? []) }], structuredContent: { orders: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-my-events.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_my_events_default = defineTool5({
  name: "list_my_events",
  title: "Eventos que eu organizo",
  description: "Lista os eventos criados pelo usu\xE1rio autenticado (produtor/organizador), incluindo rascunhos e pendentes.",
  inputSchema: {
    status: z5.string().trim().min(1).optional().describe("Filtrar por status do evento (ex.: draft, pending, published)."),
    limit: z5.number().int().min(1).max(100).default(50).describe("N\xFAmero m\xE1ximo de eventos retornados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("events").select("id, title, slug, status, start_date, end_date, city, category, created_at").eq("organizer_id", ctx.getUserId()).order("start_date", { ascending: false }).limit(limit ?? 50);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data ?? []) }], structuredContent: { events: data ?? [] } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "duasvoeejubywzoyldoa";
var mcp_default = defineMcp({
  name: "premier-pass",
  title: "Premier pass",
  version: "0.1.0",
  instructions: "Ferramentas da PremierPass (plataforma de ingressos). Use `list_events` e `get_event` para consultar eventos publicados e seus ingressos; `list_my_tickets` e `list_my_orders` para os dados do usu\xE1rio autenticado; `list_my_events` para eventos organizados por ele. Respostas em portugu\xEAs.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_events_default, get_event_default, list_my_tickets_default, list_my_orders_default, list_my_events_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
